remote_theme: fongandrew/hydeout

title:            RL @illya13
baseurl:          '/RL'
paginate:         5
google_analytics: UA-7703990-4

sidebar_blog_link:  '/'

disqus:
  shortname:      rl-at-illya13

plugins:
  - jekyll-sitemap